[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options        = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/script.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/tv_channels.json"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
